on:
  push:
    branches:
      - main

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      WORKDIR: ./payment-gateway-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install dependencies
        working-directory: ${{ env.WORKDIR }}
        run: yarn install --frozen-lockfile
      - name: Release
        working-directory: ${{ env.WORKDIR }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
